# Generated by Django 4.2.1 on 2023-05-26 20:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(blank=True, max_length=200)),
                ('a1', models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5)),
                ('q2', models.CharField(blank=True, max_length=200)),
                ('a2', models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5)),
                ('q3', models.CharField(blank=True, max_length=200)),
                ('a3', models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5)),
                ('q4', models.CharField(blank=True, max_length=200)),
                ('a4', models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5)),
                ('q5', models.CharField(blank=True, max_length=200)),
                ('a5', models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5)),
                ('msg', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FollowersCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post_images')),
                ('caption', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('no_of_likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('profileimg', models.ImageField(default='blank-profile-picture.png', upload_to='profile_images')),
                ('location', models.CharField(blank=True, choices=[('TEL AVIV', 'TEL AVIV'), ('BEER SHEVA', 'BEER SHEVA'), ('JERUSALEM', 'JERUSALEM'), ('HAIFA', 'HAIFA'), ('DIMONA', 'DIMONA'), ('RAMAT GAN', 'RAMAT GAN'), ('HERZELIA', 'HERZELIA'), ('HEDERA', 'HEDERA'), ('KIRIAT SHMONA', 'KIRIAT SHMONA'), ('ELIAT', 'ELIAT')], max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=10, null=True)),
                ('sport', models.CharField(blank=True, choices=[('SOCCER', 'SOCCER'), ('BASKETBALL', 'BASKETBALL'), ('TENNIS', 'TENNIS'), ('CYCLING', 'CYCLING')], default='SOCCER', max_length=20, null=True)),
                ('level', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('number_of_new', models.IntegerField(default=0)),
                ('preferences', models.CharField(blank=True, max_length=10000, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(default=0)),
                ('noti_text', models.TextField(blank=True)),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('notification_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('who_contacted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='who_contacted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=100)),
                ('sport', models.CharField(choices=[('SOCCER', 'SOCCER'), ('BASKETBALL', 'BASKETBALL'), ('TENNIS', 'TENNIS'), ('CYCLING', 'CYCLING')], max_length=20)),
                ('lavel', models.CharField(blank=True, default=0, max_length=20)),
                ('location', models.CharField(blank=True, choices=[('TEL AVIV', 'TEL AVIV'), ('BEER SHEVA', 'BEER SHEVA'), ('JERUSALEM', 'JERUSALEM'), ('HAIFA', 'HAIFA'), ('DIMONA', 'DIMONA'), ('RAMAT GAN', 'RAMAT GAN'), ('HERZELIA', 'HERZELIA'), ('HEDERA', 'HEDERA'), ('KIRIAT SHMONA', 'KIRIAT SHMONA'), ('ELIAT', 'ELIAT')], max_length=100)),
                ('no_of_participents', models.IntegerField(default=0)),
                ('participant_left', models.IntegerField(blank=True, default=0)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('image', models.ImageField(blank=True, upload_to='event_image/')),
                ('is_active', models.BooleanField(default=True)),
                ('feedbacks', models.ManyToManyField(blank=True, to='core.feedback')),
                ('participants', models.ManyToManyField(blank=True, to='core.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
